/* Additional popular movements. Loaded before the main application data. */
const extraExercise = (name, group, equipment, primary, secondary, cue, nlPrimary, nlSecondary, nlCue, photo) => ({
  name, group, equipment, primary, secondary, cue, photo,
  nl:{primary:nlPrimary, secondary:nlSecondary, cue:nlCue},
  icon:{stance:'standing', armL:'down', armR:'down'}
});

const EXTRA_EXERCISES = [
  // CHEST
  extraExercise('Dumbbell Bench Press','chest','dumbbell','Chest',['Triceps','Shoulders'],'Keep your shoulder blades set, lower the dumbbells beside your chest, and press them up without clashing them together.','Borst',['Triceps','Schouders'],'Houd je schouderbladen stabiel, laat de dumbbells naast je borst zakken en druk ze omhoog zonder ze tegen elkaar te slaan.','Incline_Dumbbell_Press.jpg'),
  extraExercise('Incline Push-Up','chest','bodyweight','Chest',['Triceps','Shoulders'],'Place your hands on a stable bench, keep one straight line from head to heels, and bring your chest toward the edge.','Borst',['Triceps','Schouders'],'Plaats je handen op een stabiele bank, houd één rechte lijn van hoofd tot hielen en breng je borst naar de rand.','Pushups.jpg'),
  extraExercise('Dumbbell Pullover','chest','dumbbell','Chest',['Lats','Triceps'],'Keep a soft elbow bend, lower one dumbbell behind your head only as far as your shoulders allow, then pull it over your chest.','Borst',['Lats','Triceps'],'Houd een lichte elleboogbuiging, laat één dumbbell achter je hoofd zakken binnen je schoudermobiliteit en trek hem terug boven je borst.','Decline_Dumbbell_Triceps_Extension.jpg'),
  extraExercise('Svend Press','chest','dumbbell','Chest',['Shoulders','Triceps'],'Squeeze two plates or one dumbbell between your palms and press straight forward while maintaining inward pressure.','Borst',['Schouders','Triceps'],'Klem twee schijven of één dumbbell tussen je handpalmen en druk recht vooruit terwijl je naar binnen blijft knijpen.','Front_Dumbbell_Raise.jpg'),
  extraExercise('Single-Arm Cable Chest Press','chest','cable','Chest',['Triceps','Core'],'Stand in a split stance and press one handle forward without letting the cable rotate your torso.','Borst',['Triceps','Core'],'Sta in een gespreide houding en druk één handvat vooruit zonder dat de kabel je romp laat roteren.','Cable_Crossover.jpg'),
  extraExercise('Low-to-High Cable Fly','chest','cable','Upper Chest',['Shoulders'],'Sweep the handles upward and inward toward upper-chest height while keeping your ribs down and elbows softly bent.','Bovenste borst',['Schouders'],'Breng de handvatten omhoog en naar binnen tot borsthoogte, met je ribben laag en je ellebogen licht gebogen.','Incline_Cable_Flye.jpg'),
  extraExercise('High-to-Low Cable Fly','chest','cable','Lower Chest',['Shoulders'],'Pull the handles down and together toward your front pockets, squeezing the chest without rounding your shoulders.','Onderste borst',['Schouders'],'Trek de handvatten omlaag en samen richting je broekzakken en span je borst aan zonder je schouders te ronden.','Cable_Crossover.jpg'),
  extraExercise('Smith Machine Bench Press','chest','machine','Chest',['Triceps','Shoulders'],'Set the bench so the bar reaches mid-chest, keep your wrists stacked, and press smoothly along the fixed track.','Borst',['Triceps','Schouders'],'Plaats de bank zodat de stang het midden van je borst bereikt, houd je polsen recht en druk vloeiend langs de vaste baan.','Machine_Bench_Press.jpg'),
  extraExercise('Wide-Grip Push-Up','chest','bodyweight','Chest',['Shoulders','Triceps'],'Set your hands slightly wider than shoulders and lower with control, keeping your elbows below shoulder height.','Borst',['Schouders','Triceps'],'Zet je handen iets breder dan je schouders en zak gecontroleerd, met je ellebogen onder schouderhoogte.','Pushups.jpg'),

  // BACK
  extraExercise('Neutral-Grip Lat Pulldown','back','cable','Lats',['Biceps'],'Lead with your elbows and pull the neutral handles toward your upper chest while keeping your torso nearly upright.','Lats',['Biceps'],'Leid met je ellebogen en trek de neutrale handvatten naar je bovenborst terwijl je romp bijna rechtop blijft.','Wide-Grip_Lat_Pulldown.jpg'),
  extraExercise('Kneeling Single-Arm Lat Pulldown','back','cable','Lats',['Biceps','Core'],'Kneel beside a high pulley and drive one elbow toward your hip without twisting your torso.','Lats',['Biceps','Core'],'Kniel naast een hoge katrol en trek één elleboog richting je heup zonder je romp te draaien.','Straight-Arm_Pulldown.jpg'),
  extraExercise('Meadows Row','back','barbell','Lats',['Upper Back','Biceps'],'Stand perpendicular to the landmine, brace your free hand, and row the bar end toward your hip.','Lats',['Bovenrug','Biceps'],'Sta haaks op de landmine, steun met je vrije hand en trek het uiteinde van de stang naar je heup.','Bent_Over_Barbell_Row.jpg'),
  extraExercise('Inverted Row','back','bodyweight','Mid Back',['Lats','Biceps'],'Keep your body rigid and pull your chest to the bar, finishing with your shoulder blades together.','Middenrug',['Lats','Biceps'],'Houd je lichaam stijf en trek je borst naar de stang, eindigend met je schouderbladen samen.','Pullups.jpg'),
  extraExercise('Dumbbell Shrug','back','dumbbell','Traps',['Forearms'],'Lift your shoulders straight toward your ears, pause briefly, and lower fully without rolling them.','Trapezius',['Onderarmen'],'Trek je schouders recht naar je oren, pauzeer kort en laat volledig zakken zonder te rollen.','Barbell_Shrug.jpg'),
  extraExercise('Rack Pull','back','barbell','Back',['Glutes','Hamstrings','Traps'],'Start the bar below the knees, brace hard, and stand tall by driving your hips through without leaning back.','Rug',['Bilspieren','Hamstrings','Trapezius'],'Start met de stang onder je knieën, span je romp aan en kom rechtop door je heupen naar voren te brengen zonder achterover te leunen.','Barbell_Deadlift.jpg'),
  extraExercise('Seal Row','back','barbell','Mid Back',['Lats','Biceps'],'Lie face down on a high bench and row the bar to the bench without lifting your chest.','Middenrug',['Lats','Biceps'],'Lig op je buik op een hoge bank en trek de stang naar de bank zonder je borst op te tillen.','Bent_Over_Barbell_Row.jpg'),
  extraExercise('Close-Grip Pulldown','back','cable','Lats',['Biceps'],'Pull a close handle to your lower chest with elbows close to your sides and a controlled return.','Lats',['Biceps'],'Trek een smal handvat naar je onderste borst met je ellebogen dicht langs je zij en keer gecontroleerd terug.','Wide-Grip_Lat_Pulldown.jpg'),

  // SHOULDERS
  extraExercise('Landmine Press','shoulders','barbell','Front Delts',['Upper Chest','Triceps'],'Press the bar up and forward from shoulder height, allowing your shoulder blade to rotate naturally.','Voorste schouders',['Bovenste borst','Triceps'],'Druk de stang vanaf schouderhoogte omhoog en vooruit en laat je schouderblad natuurlijk meedraaien.','Standing_Military_Press.jpg'),
  extraExercise('Push Press','shoulders','barbell','Shoulders',['Triceps','Legs'],'Use a shallow knee dip to drive the bar overhead, then finish with arms locked above your shoulders.','Schouders',['Triceps','Benen'],'Gebruik een korte kniebuiging om de stang boven je hoofd te stuwen en eindig met gestrekte armen boven je schouders.','Standing_Military_Press.jpg'),
  extraExercise('Single-Arm Dumbbell Press','shoulders','dumbbell','Shoulders',['Triceps','Core'],'Press one dumbbell overhead while keeping your ribs stacked over your pelvis and your torso upright.','Schouders',['Triceps','Core'],'Druk één dumbbell boven je hoofd terwijl je ribben boven je bekken blijven en je romp rechtop staat.','Dumbbell_Shoulder_Press.jpg'),
  extraExercise('Lean-Away Cable Lateral Raise','shoulders','cable','Side Delts',['Traps'],'Hold the cable tower, lean slightly away, and raise the outside arm to shoulder height without shrugging.','Zijdelingse schouders',['Trapezius'],'Houd de kabeltoren vast, leun licht weg en hef de buitenste arm tot schouderhoogte zonder op te trekken.','Cable_Seated_Lateral_Raise.jpg'),
  extraExercise('Incline Y-Raise','shoulders','dumbbell','Lower Traps',['Rear Delts','Shoulders'],'Lie chest-down on an incline bench and raise light dumbbells in a Y shape with thumbs up.','Onderste trapezius',['Achterste schouders','Schouders'],'Lig met je borst op een schuine bank en hef lichte dumbbells in een Y-vorm met je duimen omhoog.','Reverse_Flyes.jpg'),
  extraExercise('Cuban Press','shoulders','dumbbell','Shoulders',['Rotator Cuff','Traps'],'Row the weights to chest height, rotate the forearms upward, then press overhead using a light load.','Schouders',['Rotator cuff','Trapezius'],'Trek de gewichten tot borsthoogte, roteer je onderarmen omhoog en druk dan met een licht gewicht boven je hoofd.','Dumbbell_Shoulder_Press.jpg'),
  extraExercise('Plate Front Raise','shoulders','dumbbell','Front Delts',['Upper Chest'],'Raise a plate to shoulder height with soft elbows and lower it without swinging your torso.','Voorste schouders',['Bovenste borst'],'Hef een schijf tot schouderhoogte met licht gebogen ellebogen en laat zakken zonder met je romp te zwaaien.','Front_Dumbbell_Raise.jpg'),
  extraExercise('Dumbbell Upright Row','shoulders','dumbbell','Side Delts',['Traps'],'Pull the dumbbells along your torso until your elbows reach shoulder height, keeping wrists below elbows.','Zijdelingse schouders',['Trapezius'],'Trek de dumbbells langs je romp tot je ellebogen schouderhoogte bereiken, met je polsen onder je ellebogen.','Upright_Barbell_Row.jpg'),
  extraExercise('Pike Push-Up','shoulders','bodyweight','Shoulders',['Triceps','Upper Chest'],'Keep your hips high and lower the top of your head between your hands, then press the floor away.','Schouders',['Triceps','Bovenste borst'],'Houd je heupen hoog, laat de bovenkant van je hoofd tussen je handen zakken en duw de vloer weg.','Pushups.jpg'),

  // BICEPS
  extraExercise('Bayesian Cable Curl','biceps','cable','Biceps',['Forearms'],'Face away from a low pulley with your arm slightly behind you and curl without letting your shoulder drift forward.','Biceps',['Onderarmen'],'Sta van een lage katrol weg met je arm licht achter je en curl zonder je schouder naar voren te laten bewegen.','Standing_Biceps_Cable_Curl.jpg'),
  extraExercise('Drag Curl','biceps','barbell','Biceps',['Forearms'],'Drag the bar up your torso while pulling your elbows behind you, then lower along the same path.','Biceps',['Onderarmen'],'Sleep de stang langs je romp omhoog terwijl je ellebogen naar achter gaan en laat langs dezelfde baan zakken.','Barbell_Curl.jpg'),
  extraExercise('Cross-Body Hammer Curl','biceps','dumbbell','Brachialis',['Biceps','Forearms'],'Curl the dumbbell toward the opposite shoulder with a neutral grip and keep your elbow close to your ribs.','Brachialis',['Biceps','Onderarmen'],'Curl de dumbbell met neutrale greep naar de tegenovergestelde schouder en houd je elleboog dicht bij je ribben.','Hammer_Curls.jpg'),
  extraExercise('Machine Biceps Curl','biceps','machine','Biceps',['Forearms'],'Align your elbows with the machine pivot and curl through a full range without lifting them from the pad.','Biceps',['Onderarmen'],'Lijn je ellebogen uit met het draaipunt van de machine en curl volledig zonder ze van de pad te tillen.','Preacher_Curl.jpg'),
  extraExercise('Reverse-Grip EZ-Bar Curl','biceps','barbell','Brachialis',['Forearms','Biceps'],'Use an overhand grip and curl the EZ-bar while keeping your wrists neutral and elbows fixed.','Brachialis',['Onderarmen','Biceps'],'Gebruik een bovenhandse greep en curl de EZ-stang met neutrale polsen en vaste ellebogen.','EZ-Bar_Curl.jpg'),
  extraExercise('High Cable Curl','biceps','cable','Biceps',['Forearms'],'Set both pulleys high and curl your hands toward your ears while keeping your upper arms level.','Biceps',['Onderarmen'],'Zet beide katrollen hoog en curl je handen naar je oren terwijl je bovenarmen horizontaal blijven.','Standing_Biceps_Cable_Curl.jpg'),
  extraExercise('Waiter Curl','biceps','dumbbell','Biceps',['Forearms'],'Hold one dumbbell vertically under the top plate and curl it toward your chest without bending your wrists.','Biceps',['Onderarmen'],'Houd één dumbbell verticaal onder de bovenste schijf en curl naar je borst zonder je polsen te buigen.','Concentration_Curls.jpg'),
  extraExercise('Dumbbell Preacher Curl','biceps','dumbbell','Biceps',['Forearms'],'Support your upper arm on the pad and curl one dumbbell without losing contact at the bottom.','Biceps',['Onderarmen'],'Steun je bovenarm op de pad en curl één dumbbell zonder onderaan het contact te verliezen.','Preacher_Curl.jpg'),
  extraExercise('Barbell Spider Curl','biceps','barbell','Biceps',['Forearms'],'Lie chest-down on an incline bench and curl the bar while your upper arms hang vertically.','Biceps',['Onderarmen'],'Lig met je borst op een schuine bank en curl de stang terwijl je bovenarmen verticaal hangen.','Spider_Curl.jpg'),
  extraExercise('Strict Barbell Curl','biceps','barbell','Biceps',['Forearms'],'Stand with your back against a wall and curl without moving your shoulders or hips away from it.','Biceps',['Onderarmen'],'Sta met je rug tegen een muur en curl zonder je schouders of heupen ervan weg te bewegen.','Barbell_Curl.jpg'),

  // TRICEPS
  extraExercise('Overhead EZ-Bar Extension','triceps','barbell','Triceps',['Shoulders'],'Keep your upper arms near your ears, lower the EZ-bar behind your head, and extend without flaring wide.','Triceps',['Schouders'],'Houd je bovenarmen bij je oren, laat de EZ-stang achter je hoofd zakken en strek zonder breed uit te waaieren.','EZ-Bar_Skullcrusher.jpg'),
  extraExercise('Single-Arm Overhead Dumbbell Extension','triceps','dumbbell','Triceps',['Shoulders'],'Point one elbow upward and extend the dumbbell overhead while keeping your ribs down.','Triceps',['Schouders'],'Richt één elleboog omhoog en strek de dumbbell boven je hoofd terwijl je ribben laag blijven.','Decline_Dumbbell_Triceps_Extension.jpg'),
  extraExercise('Reverse-Grip Cable Pushdown','triceps','cable','Triceps',[],'Use an underhand grip and straighten your elbows fully while keeping them pinned beside your torso.','Triceps',[],'Gebruik een onderhandse greep en strek je ellebogen volledig terwijl ze naast je romp vast blijven.','Triceps_Pushdown.jpg'),
  extraExercise('Tate Press','triceps','dumbbell','Triceps',['Chest'],'Lie on a bench, lower the dumbbell heads toward your chest with elbows wide, then extend them upward.','Triceps',['Borst'],'Lig op een bank, laat de koppen van de dumbbells richting je borst zakken met brede ellebogen en strek omhoog.','Decline_Dumbbell_Triceps_Extension.jpg'),
  extraExercise('Floor Skull Crusher','triceps','barbell','Triceps',['Shoulders'],'Lie on the floor and lower the bar behind your head until the plates lightly touch down, then extend.','Triceps',['Schouders'],'Lig op de vloer en laat de stang achter je hoofd zakken tot de schijven licht de grond raken en strek dan.','EZ-Bar_Skullcrusher.jpg'),
  extraExercise('Assisted Dip','triceps','machine','Triceps',['Chest','Shoulders'],'Use enough assistance to keep your torso upright and lower until your elbows reach about 90 degrees.','Triceps',['Borst','Schouders'],'Gebruik voldoende ondersteuning om rechtop te blijven en zak tot je ellebogen ongeveer 90 graden bereiken.','Dips_-_Triceps_Version.jpg'),
  extraExercise('Dumbbell Close-Grip Press','triceps','dumbbell','Triceps',['Chest'],'Press two dumbbells together above your chest and keep squeezing them as you lower and press.','Triceps',['Borst'],'Druk twee dumbbells tegen elkaar boven je borst en blijf knijpen terwijl je zakt en drukt.','Incline_Dumbbell_Press.jpg'),
  extraExercise('Bodyweight Triceps Extension','triceps','bodyweight','Triceps',['Core','Shoulders'],'Grip a stable bar, keep your body rigid, and bend only your elbows to bring your forehead toward it.','Triceps',['Core','Schouders'],'Grijp een stabiele stang, houd je lichaam stijf en buig alleen je ellebogen om je voorhoofd naar de stang te brengen.','Pushups.jpg'),

  // ABS & CORE
  extraExercise('Hollow Body Hold','abs','bodyweight','Core',['Hip Flexors'],'Press your lower back into the floor and extend arms and legs only as far as you can maintain contact.','Core',['Heupbuigers'],'Druk je onderrug in de vloer en strek armen en benen alleen zo ver als je contact kunt houden.','Plank.jpg'),
  extraExercise('Bicycle Crunch','abs','bodyweight','Obliques',['Abs','Hip Flexors'],'Rotate shoulder to opposite knee while extending the other leg, moving slowly instead of pulling your neck.','Schuine buikspieren',['Buikspieren','Heupbuigers'],'Draai je schouder naar de tegenovergestelde knie terwijl je het andere been strekt en beweeg traag zonder aan je nek te trekken.','Crunches.jpg'),
  extraExercise('V-Up','abs','bodyweight','Abs',['Hip Flexors'],'Lift your straight legs and torso together, reaching toward your feet while balancing briefly on your hips.','Buikspieren',['Heupbuigers'],'Hef je gestrekte benen en romp tegelijk en reik naar je voeten terwijl je kort op je heupen balanceert.','Reverse_Crunch.jpg'),
  extraExercise('Toe Touch Crunch','abs','bodyweight','Upper Abs',[],'Hold your legs vertical and lift your shoulder blades as you reach toward your toes.','Bovenste buikspieren',[],'Houd je benen verticaal en til je schouderbladen op terwijl je naar je tenen reikt.','Crunches.jpg'),
  extraExercise('Bird Dog','abs','bodyweight','Core',['Glutes','Shoulders'],'From all fours, extend opposite arm and leg while keeping your hips square and lower back still.','Core',['Bilspieren','Schouders'],'Strek vanuit handen en knieën de tegenovergestelde arm en het been terwijl je heupen recht en onderrug stil blijven.','Superman.jpg'),
  extraExercise('Bear Plank','abs','bodyweight','Core',['Shoulders','Quads'],'Hover your knees just above the floor with hands under shoulders and keep your back flat while breathing.','Core',['Schouders','Quads'],'Laat je knieën net boven de vloer zweven met handen onder je schouders en houd je rug vlak terwijl je ademt.','Plank.jpg'),
  extraExercise('Copenhagen Plank','abs','bodyweight','Obliques',['Adductors','Shoulders'],'Support your top leg on a bench, lift your hips, and keep a straight line through your body.','Schuine buikspieren',['Adductoren','Schouders'],'Steun je bovenste been op een bank, hef je heupen en houd een rechte lijn door je lichaam.','Side_Bridge.jpg'),
  extraExercise('Cable Anti-Rotation Hold','abs','cable','Core',['Obliques','Glutes'],'Stand side-on to the cable, hold the handle in front of your chest, and resist every pull to rotate.','Core',['Schuine buikspieren','Bilspieren'],'Sta zijwaarts aan de kabel, houd het handvat voor je borst en weersta elke trekkracht die je wil roteren.','Standing_Cable_Wood_Chop.jpg'),
  extraExercise('Dragon Flag','abs','bodyweight','Core',['Hip Flexors','Lats'],'Brace on a bench, raise your body as one rigid line, and lower slowly without letting your hips fold.','Core',['Heupbuigers','Lats'],'Zet je vast aan een bank, hef je lichaam als één stijve lijn en zak traag zonder je heupen te plooien.','Reverse_Crunch.jpg'),

  // LEGS
  extraExercise('Box Squat','legs','barbell','Quads',['Glutes','Hamstrings'],'Sit back to a box under control, pause without relaxing, and drive through your full foot to stand.','Quads',['Bilspieren','Hamstrings'],'Zak gecontroleerd naar een box, pauzeer zonder te ontspannen en duw via je hele voet terug omhoog.','Barbell_Squat.jpg'),
  extraExercise('Smith Machine Squat','legs','machine','Quads',['Glutes'],'Place your feet slightly forward, keep your back neutral, and squat smoothly along the fixed path.','Quads',['Bilspieren'],'Plaats je voeten iets naar voren, houd je rug neutraal en squat vloeiend langs de vaste baan.','Hack_Squat.jpg'),
  extraExercise('Reverse Lunge','legs','dumbbell','Quads',['Glutes','Hamstrings'],'Step back far enough for both knees to bend comfortably, then push through the front foot to return.','Quads',['Bilspieren','Hamstrings'],'Stap ver genoeg achteruit zodat beide knieën comfortabel buigen en duw via je voorste voet terug.','Dumbbell_Rear_Lunge.jpg'),
  extraExercise('Lateral Lunge','legs','dumbbell','Quads',['Glutes','Adductors'],'Step wide to one side, sit into that hip, and keep the other leg long with both feet flat.','Quads',['Bilspieren','Adductoren'],'Stap breed opzij, zak in die heup en houd het andere been lang met beide voeten plat.','Barbell_Side_Split_Squat.jpg'),
  extraExercise('Step-Down','legs','bodyweight','Quads',['Glutes'],'Stand on a step and lower one heel toward the floor while keeping the stance knee aligned over the foot.','Quads',['Bilspieren'],'Sta op een opstap en laat één hiel richting de vloer zakken terwijl de standknie boven de voet blijft.','Barbell_Step_Ups.jpg'),
  extraExercise('Spanish Squat','legs','bodyweight','Quads',[],'Lean back against a sturdy strap behind the knees and sit down with an upright torso before driving up.','Quads',[],'Leun achteruit tegen een stevige band achter je knieën en zak met rechte romp voordat je omhoog duwt.','Weighted_Sissy_Squat.jpg'),
  extraExercise('Belt Squat','legs','machine','Quads',['Glutes'],'Attach the load at your hips, stay upright, and squat deeply while keeping your knees aligned with your toes.','Quads',['Bilspieren'],'Bevestig de belasting aan je heupen, blijf rechtop en squat diep met je knieën in lijn met je tenen.','Hack_Squat.jpg'),
  extraExercise('Pendulum Squat','legs','machine','Quads',['Glutes'],'Keep your back against the pad and descend through the machine arc without letting your heels lift.','Quads',['Bilspieren'],'Houd je rug tegen de pad en zak langs de machineboog zonder je hielen op te tillen.','Hack_Squat.jpg'),
  extraExercise('Seated Leg Curl','legs','machine','Hamstrings',[],'Pin your thighs down, curl the pad under the seat, and return slowly to a full hamstring stretch.','Hamstrings',[],'Zet je dijen vast, curl de pad onder de zitting en keer traag terug naar volledige rek.','Lying_Leg_Curls.jpg'),
  extraExercise('Nordic Hamstring Curl','legs','bodyweight','Hamstrings',['Glutes'],'Anchor your ankles and lower your straight body as slowly as possible, catching yourself with your hands if needed.','Hamstrings',['Bilspieren'],'Veranker je enkels en laat je gestrekte lichaam zo traag mogelijk zakken, eventueel opgevangen met je handen.','Glute_Ham_Raise.jpg'),

  // GLUTES
  extraExercise('Frog Pump','glutes','bodyweight','Glutes',['Hamstrings'],'Press the soles of your feet together, open your knees, and drive your hips up by squeezing your glutes.','Bilspieren',['Hamstrings'],'Druk je voetzolen tegen elkaar, open je knieën en hef je heupen door je bilspieren aan te spannen.','Butt_Lift_Bridge.jpg'),
  extraExercise('B-Stance Hip Thrust','glutes','barbell','Glutes',['Hamstrings'],'Place one foot slightly forward as a kickstand and drive mainly through the heel of the working leg.','Bilspieren',['Hamstrings'],'Plaats één voet licht vooruit als steun en duw vooral via de hiel van het werkende been.','Barbell_Hip_Thrust.jpg'),
  extraExercise('Single-Leg Hip Thrust','glutes','bodyweight','Glutes',['Hamstrings'],'Brace your upper back on a bench, lift one foot, and drive the working hip up without rotating.','Bilspieren',['Hamstrings'],'Steun met je bovenrug op een bank, hef één voet en duw de werkende heup omhoog zonder te roteren.','Single_Leg_Glute_Bridge.jpg'),
  extraExercise('Dumbbell Hip Thrust','glutes','dumbbell','Glutes',['Hamstrings'],'Secure a dumbbell across your hips and finish each rep with full hip extension and ribs down.','Bilspieren',['Hamstrings'],'Houd een dumbbell over je heupen en eindig elke herhaling met volledige heupstrekking en lage ribben.','Barbell_Hip_Thrust.jpg'),
  extraExercise('Smith Machine Hip Thrust','glutes','machine','Glutes',['Hamstrings'],'Center the padded bar over your hips and drive upward along the fixed track without overextending your back.','Bilspieren',['Hamstrings'],'Centreer de gevoerde stang over je heupen en duw omhoog langs de vaste baan zonder je rug te overstrekken.','Barbell_Hip_Thrust.jpg'),
  extraExercise('Standing Cable Hip Abduction','glutes','cable','Glute Medius',['Hip Abductors'],'Stand tall and move one leg out to the side without leaning or turning the toes upward.','Gluteus medius',['Heupabductoren'],'Sta rechtop en beweeg één been zijwaarts zonder te leunen of de tenen omhoog te draaien.','Thigh_Abductor.jpg'),
  extraExercise('Lateral Band Walk','glutes','bodyweight','Glute Medius',['Quads'],'Stay in a shallow squat and take controlled side steps while keeping constant outward tension.','Gluteus medius',['Quads'],'Blijf in een lichte squat en zet gecontroleerde zijstappen met constante spanning naar buiten.','Thigh_Abductor.jpg'),
  extraExercise('Clamshell','glutes','bodyweight','Glute Medius',[],'Lie on your side with bent knees and open the top knee without rolling your pelvis backward.','Gluteus medius',[],'Lig op je zij met gebogen knieën en open de bovenste knie zonder je bekken achteruit te rollen.','Thigh_Abductor.jpg'),
  extraExercise('Fire Hydrant','glutes','bodyweight','Glute Medius',['Core'],'From all fours, lift one bent knee out to the side while keeping your hips level and spine still.','Gluteus medius',['Core'],'Hef vanuit handen en knieën één gebogen knie zijwaarts terwijl je heupen gelijk en wervelkolom stil blijven.','Glute_Kickback.jpg'),
  extraExercise('Curtsy Lunge','glutes','dumbbell','Glutes',['Quads','Adductors'],'Step one leg diagonally behind the other and lower with your front knee tracking over your foot.','Bilspieren',['Quads','Adductoren'],'Stap één been diagonaal achter het andere en zak met je voorste knie in lijn boven je voet.','Dumbbell_Rear_Lunge.jpg'),

  // CALVES
  extraExercise('Single-Leg Standing Calf Raise','calves','bodyweight','Calves',[],'Balance on one foot, lower the heel fully, and rise as high as possible without rolling the ankle.','Kuiten',[],'Balanceer op één voet, laat je hiel volledig zakken en kom zo hoog mogelijk zonder je enkel te rollen.','Standing_Calf_Raises.jpg'),
  extraExercise('Leg Press Calf Raise','calves','machine','Calves',[],'Keep your knees nearly straight and move the platform only through your ankles with a deep stretch.','Kuiten',[],'Houd je knieën bijna gestrekt en beweeg het platform alleen via je enkels met een diepe rek.','Standing_Calf_Raises.jpg'),
  extraExercise('Smith Machine Seated Calf Raise','calves','machine','Soleus',[],'Sit with the Smith bar padded over your thighs and raise your heels through a full range.','Soleus',[],'Zit met de gevoerde Smith-stang over je dijen en hef je hielen door het volledige bewegingsbereik.','Smith_Machine_Calf_Raise.jpg'),
  extraExercise('Tibialis Raise','calves','bodyweight','Tibialis Anterior',[],'Lean against a wall with heels planted and lift your toes toward your shins before lowering slowly.','Voorste scheenbeenspier',[],'Leun tegen een muur met je hielen op de grond en trek je tenen naar je schenen voordat je traag zakt.','Rocking_Standing_Calf_Raise.jpg'),
  extraExercise('Bent-Knee Standing Calf Raise','calves','bodyweight','Soleus',[],'Hold a shallow squat, keep the knees bent, and raise both heels while your torso stays still.','Soleus',[],'Houd een lichte squat, laat je knieën gebogen en hef beide hielen terwijl je romp stil blijft.','Standing_Calf_Raises.jpg'),
  extraExercise('Single-Leg Seated Calf Raise','calves','dumbbell','Soleus',[],'Place a dumbbell above one knee and raise that heel slowly from a full stretch to a hard squeeze.','Soleus',[],'Plaats een dumbbell boven één knie en hef die hiel traag van volledige rek naar maximale spanning.','Dumbbell_Seated_One-Leg_Calf_Raise.jpg'),
  extraExercise('Bodyweight Donkey Calf Raise','calves','bodyweight','Calves',[],'Hinge at the hips with hands supported and raise your heels high while keeping your legs nearly straight.','Kuiten',[],'Buig vanuit je heupen met je handen gesteund en hef je hielen hoog met bijna gestrekte benen.','Donkey_Calf_Raises.jpg'),
  extraExercise('Paused Calf Raise','calves','machine','Calves',[],'Pause for two seconds in the stretched bottom position and again at the top of every repetition.','Kuiten',[],'Pauzeer twee seconden in de onderste rekpositie en opnieuw bovenaan elke herhaling.','Smith_Machine_Calf_Raise.jpg'),
  extraExercise('Explosive Calf Raise','calves','bodyweight','Calves',['Ankles'],'Drive quickly onto the balls of your feet, land softly, and reset your balance before the next rep.','Kuiten',['Enkels'],'Duw snel op de bal van je voeten, land zacht en herstel je balans voor de volgende herhaling.','Standing_Calf_Raises.jpg'),

  // FOREARMS
  extraExercise('Barbell Wrist Curl','forearms','barbell','Forearm Flexors',[],'Rest your forearms on a bench with palms up and curl the bar using only your wrists.','Onderarmbuigers',[],'Steun je onderarmen op een bank met handpalmen omhoog en curl de stang alleen met je polsen.','Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench.jpg'),
  extraExercise('Reverse Dumbbell Wrist Curl','forearms','dumbbell','Forearm Extensors',[],'Support your forearms palms-down and lift the backs of your hands without moving your elbows.','Onderarmstrekkers',[],'Steun je onderarmen met handpalmen omlaag en hef de rug van je handen zonder je ellebogen te bewegen.','Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench.jpg'),
  extraExercise('Dumbbell Pronation and Supination','forearms','dumbbell','Forearms',[],'Hold one end of a light dumbbell and rotate the forearm slowly through a comfortable range.','Onderarmen',[],'Houd één uiteinde van een lichte dumbbell vast en roteer je onderarm traag door een comfortabel bereik.','Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench.jpg'),
  extraExercise('Towel Hang','forearms','bodyweight','Grip',['Lats','Shoulders'],'Drape a sturdy towel over a pull-up bar and hang with shoulders active and a firm crush grip.','Grip',['Lats','Schouders'],'Hang een stevige handdoek over een optrekstang en hang met actieve schouders en een stevige knijpgreep.','Pullups.jpg'),
  extraExercise('Dead Hang','forearms','bodyweight','Grip',['Lats','Shoulders'],'Hang from the bar with a full grip, keep your shoulders gently active, and breathe steadily.','Grip',['Lats','Schouders'],'Hang met volledige greep aan de stang, houd je schouders licht actief en adem rustig.','Pullups.jpg'),
  extraExercise('Dumbbell Suitcase Hold','forearms','dumbbell','Grip',['Core','Obliques'],'Hold one heavy dumbbell at your side and stay perfectly upright for the full timed set.','Grip',['Core','Schuine buikspieren'],'Houd één zware dumbbell naast je en blijf de hele tijd perfect rechtop.','Farmers_Walk.jpg'),
  extraExercise('Cable Wrist Curl','forearms','cable','Forearm Flexors',[],'Hold a low cable with palms up and flex only at the wrists while your forearms stay still.','Onderarmbuigers',[],'Houd een lage kabel met handpalmen omhoog en buig alleen je polsen terwijl je onderarmen stil blijven.','Standing_Biceps_Cable_Curl.jpg'),
  extraExercise('Cable Reverse Wrist Curl','forearms','cable','Forearm Extensors',[],'Grip a low cable palms-down and extend your wrists without lifting your elbows.','Onderarmstrekkers',[],'Grijp een lage kabel met handpalmen omlaag en strek je polsen zonder je ellebogen op te tillen.','Reverse_Cable_Curl.jpg'),
  extraExercise('Wrist Extension on Bench','forearms','dumbbell','Forearm Extensors',[],'Rest your forearms on a bench, let the hands hang off, and extend the wrists with a light load.','Onderarmstrekkers',[],'Steun je onderarmen op een bank, laat je handen over de rand hangen en strek je polsen met een licht gewicht.','Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench.jpg')
];
